CREATE TABLE IF NOT EXISTS stock_factor_daily (
  code VARCHAR(12) NOT NULL,
  trade_date DATE NOT NULL,
  ma5 DECIMAL(18,8),
  ma10 DECIMAL(18,8),
  ma20 DECIMAL(18,8),
  ma60 DECIMAL(18,8),
  ema5 DECIMAL(18,8),
  ema10 DECIMAL(18,8),
  ema20 DECIMAL(18,8),
  ema60 DECIMAL(18,8),
  rsi14 DECIMAL(18,8),
  macd DECIMAL(18,8),
  macd_signal DECIMAL(18,8),
  macd_hist DECIMAL(18,8),
  boll_mid DECIMAL(18,8),
  boll_up DECIMAL(18,8),
  boll_low DECIMAL(18,8),
  kdj_k DECIMAL(18,8),
  kdj_d DECIMAL(18,8),
  kdj_j DECIMAL(18,8),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_stock_factor_daily_code_date (code, trade_date),
  KEY idx_stock_factor_daily_trade_date (trade_date),
  KEY idx_stock_factor_daily_code (code)
);
